#fos_rest:
#  disable_csrf_role: ROLE_API
#  access_denied_listener:
#    enabled: true
#    json: true
#  param_fetcher_listener: true
#  view:
#    mime_types:
#      json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1']
#    view_response_listener: 'force'
#    formats:
#      xml: false
#      json: true
#    templating_formats:
#      html: true
#  format_listener:
#    rules:
#      - { path: '^/api', priorities: [ 'json' ], fallback_format: json, prefer_extension: true }
#      - { path: '^/', priorities: [ 'text/html','json', 'html' ], fallback_format: html, prefer_extension: true }
#  exception:
#    codes:
#      'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
#      'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
#    messages:
#      'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
#  allowed_methods_listener: true
#  body_listener: true